from ...shared.YamlFetcher.YamlFetcher import YamlFetcher
import openai

class ChatGpt:
    def __init__(self):
        self.api_key = YamlFetcher.fetch("chatgpt", "API_Keys.yaml")

    def get_response(self, request):
        '''
        Gets a response, which is generated by ChatGPT.

        Parameters: request
        Returns: answer (string)
        '''
        response = openai.completions.create(
        model="gpt-3.5-turbo",
        prompt=request
        )
        return response.choices[0].text.strip()
        
# if __name__ == "__main__":
#     myObj = ChatMaker('')
#     respones = myObj.get_response("Write a tagline for an ice cream shop.")
