# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install PortAudio development files
        run: |
          sudo apt-get update
          sudo apt-get install portaudio19-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          python -m pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        working-directory: ./src
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YELP_SECRET: ${{ secrets.YELP_SECRET }}
          NEWSAPI_SECRET: ${{ secrets.NEWSAPI_SECRET }}
          DEUTSCHEBAHN_CLIENT_ID: ${{ secrets.DEUTSCHEBAHN_CLIENT_ID }}
          DEUTSCHEBAHN_SECRET: ${{ secrets.DEUTSCHEBAHN_SECRET }}
        run: |
          pytest

      - name: Debug Environment Variables
        run: env
      
      - name: Debug Environment Variables 2
        run: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY"
          echo "YELP_SECRET=$YELP_SECRET"
          echo "NEWSAPI_SECRET=$NEWSAPI_SECRET"
          echo "DEUTSCHEBAHN_CLIENT_ID=$DEUTSCHEBAHN_CLIENT_ID"
          echo "DEUTSCHEBAHN_SECRET=$DEUTSCHEBAHN_SECRET"
          echo "NEWSAPI_SECRET=$NEWSAPI_SECRET"
